"""One-time script: strip enabled:timestamp from the canonical event log."""
import pandas as pd
import shutil

s6_path = 'data/processed/CTB/s6_eventlog_target_rank_features.csv'
backup_path = 'data/processed/CTB/s6_eventlog_target_rank_features_WITH_ENABLED_BACKUP.csv'

shutil.copy2(s6_path, backup_path)
print(f'Backup: {backup_path}')

df = pd.read_csv(s6_path)
n_events = len(df)
n_cases = df['case:concept:name'].nunique()
print(f'BEFORE: {n_events:,} events, {n_cases:,} cases, {len(df.columns)} cols')
print(f'  enabled:timestamp present: {"enabled:timestamp" in df.columns}')

if 'enabled:timestamp' in df.columns:
    df = df.drop(columns=['enabled:timestamp'])

print(f'AFTER:  {len(df):,} events, {df["case:concept:name"].nunique():,} cases, {len(df.columns)} cols')
print(f'  enabled:timestamp present: {"enabled:timestamp" in df.columns}')
print(f'Activities:')
print(df['concept:name'].value_counts().to_string())

assert len(df) == n_events, "Event count changed!"
assert df['case:concept:name'].nunique() == n_cases, "Case count changed!"
assert 'enabled:timestamp' not in df.columns

df.to_csv(s6_path, index=False)
print(f'\nSaved corrected s6 -> {s6_path}')

# Also strip from train/test if they exist
for split in ['s6_train.csv', 's6_test.csv']:
    p = f'data/processed/CTB/{split}'
    try:
        sdf = pd.read_csv(p)
        if 'enabled:timestamp' in sdf.columns:
            sdf = sdf.drop(columns=['enabled:timestamp'])
            sdf.to_csv(p, index=False)
            print(f'Stripped enabled:timestamp from {split}')
        else:
            print(f'{split}: no enabled:timestamp to strip')
    except FileNotFoundError:
        print(f'{split}: not found (will be regenerated by train_test_split)')
