"""Hard validation gates for CTB case structure and temporal causality.

This stage distinguishes two notions that must not be conflated:

* observed timestamps remain untouched, including tiny measurement overlaps;
* the process-control order is Gate In -> one or more sequential yard events
  -> Gate Out.

The real holdout must satisfy the structural contract.  The simulated log must
also satisfy strict timestamp causality because its timestamps are generated by
the simulation model rather than measured by heterogeneous source systems.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))
from _eventlog_contract import (  # noqa: E402
    ACT_COL,
    CASE_COL,
    GATE_ACTIVITIES,
    ORDER_COL,
    TS_COMPLETE,
    TS_START,
    EventLogContractError,
    canonicalize_case_order,
    eventlog_contract_report,
    validate_eventlog_contract,
)


DEFAULT_REAL = Path("data") / "processed" / "CTB" / "s6_test.csv"
DEFAULT_OUT_ROOT = Path("validation") / "results"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--real", type=Path, default=DEFAULT_REAL)
    parser.add_argument("--sim", type=Path, required=True)
    parser.add_argument("--label", required=True)
    parser.add_argument("--out-root", type=Path, default=DEFAULT_OUT_ROOT)
    parser.add_argument(
        "--real-overlap-tolerance-min",
        type=float,
        default=2.0,
        help="Reporting tolerance for small source-system timestamp overlaps.",
    )
    parser.add_argument(
        "--fail-on-sim-violations",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Return a non-zero exit code if any simulated case violates the contract.",
    )
    return parser.parse_args()


def _load(path: Path, label: str) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"[{label}] Event log not found: {path.resolve()}")
    df = pd.read_csv(path)
    df = df.loc[:, ~df.columns.duplicated()].copy()
    for col in (TS_START, TS_COMPLETE):
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")
    missing = {CASE_COL, ACT_COL, TS_START, TS_COMPLETE}.difference(df.columns)
    if missing:
        raise KeyError(f"[{label}] Missing required columns: {sorted(missing)}")
    return df


def _duration_audit(df: pd.DataFrame) -> dict:
    service = (df[TS_COMPLETE] - df[TS_START]).dt.total_seconds().div(60.0)
    grouped = df.groupby(CASE_COL, sort=False)
    turnaround = (
        grouped[TS_COMPLETE].max() - grouped[TS_START].min()
    ).dt.total_seconds().div(60.0)

    def summarize(values: pd.Series) -> dict:
        values = pd.to_numeric(values, errors="coerce").replace(
            [np.inf, -np.inf], np.nan
        ).dropna()
        return {
            "n": int(len(values)),
            "negative": int((values < 0).sum()),
            "over_24h": int((values > 24 * 60).sum()),
            "mean_min": float(values.mean()) if len(values) else float("nan"),
            "p99_min": float(values.quantile(0.99)) if len(values) else float("nan"),
            "max_min": float(values.max()) if len(values) else float("nan"),
        }

    return {
        "service_time": summarize(service),
        "case_turnaround": summarize(turnaround),
    }


def _routing_comparison(real: pd.DataFrame, sim: pd.DataFrame) -> pd.DataFrame:
    activities = sorted(set(real[ACT_COL].astype(str)) | set(sim[ACT_COL].astype(str)))
    real_counts = real[ACT_COL].astype(str).value_counts()
    sim_counts = sim[ACT_COL].astype(str).value_counts()
    real_cases = max(1, real[CASE_COL].nunique())
    sim_cases = max(1, sim[CASE_COL].nunique())
    rows = []
    for activity in activities:
        real_count = int(real_counts.get(activity, 0))
        sim_count = int(sim_counts.get(activity, 0))
        real_per_case = real_count / real_cases
        sim_per_case = sim_count / sim_cases
        rows.append(
            {
                "activity": activity,
                "real_events": real_count,
                "sim_events": sim_count,
                "real_events_per_case": real_per_case,
                "sim_events_per_case": sim_per_case,
                "relative_rate_error": (
                    (sim_per_case - real_per_case) / real_per_case
                    if real_per_case > 0
                    else float("nan")
                ),
            }
        )
    return pd.DataFrame(rows)


def _case_length_distribution(df: pd.DataFrame) -> dict[str, int]:
    counts = df.groupby(CASE_COL, sort=False).size().value_counts().sort_index()
    return {str(int(length)): int(cases) for length, cases in counts.items()}


def main() -> int:
    args = parse_args()
    out_dir = args.out_root / args.label
    out_dir.mkdir(parents=True, exist_ok=True)

    real = _load(args.real, "real")
    sim = _load(args.sim, "sim")

    # The persisted real order is authoritative.  Legacy files without the
    # explicit column are migrated from their existing yard row order.
    real = canonicalize_case_order(real)
    real_report = validate_eventlog_contract(
        real,
        label="real holdout",
        overlap_tolerance_min=args.real_overlap_tolerance_min,
        _already_ordered=True,
    )
    # Report real timestamp peculiarities, but never rewrite the observations.
    real_report = eventlog_contract_report(
        real,
        overlap_tolerance_min=args.real_overlap_tolerance_min,
        _already_ordered=True,
    )

    # ProSiT writes events in firing order while globally interleaving cases.
    # Capture that per-case order before auditing; canonicalizing by activity
    # rank would otherwise hide an early Gate Out in a defective simulation.
    sim = sim.copy()
    sim[ORDER_COL] = sim.groupby(CASE_COL, sort=False).cumcount()
    sim_report = eventlog_contract_report(sim, _already_ordered=True)

    hard_sim_keys = (
        "gate_only_cases",
        "invalid_gate_in_count_cases",
        "invalid_gate_out_count_cases",
        "wrong_case_boundary_cases",
        "within_case_overlap_cases",
        "decreasing_completion_cases",
        "negative_service_events",
        "gate_out_before_final_yard_cases",
    )
    sim_failures = {
        key: int(sim_report.get(key, 0))
        for key in hard_sim_keys
        if sim_report.get(key, 0)
    }

    routing = _routing_comparison(real, sim)
    routing.to_csv(out_dir / "routing_comparison.csv", index=False)

    result = {
        "contract": ["Gate In", "one_or_more_sequential_yard_events", "Gate Out"],
        "real_path": str(args.real),
        "sim_path": str(args.sim),
        "real": real_report,
        "sim": sim_report,
        "sim_hard_failures": sim_failures,
        "duration_audit": {
            "real": _duration_audit(real),
            "sim": _duration_audit(sim),
        },
        "case_length_distribution": {
            "real": _case_length_distribution(real),
            "sim": _case_length_distribution(sim),
        },
    }
    result_path = out_dir / "eventlog_contract.json"
    result_path.write_text(json.dumps(result, indent=2, default=str), encoding="utf-8")

    print("[contract] Real log")
    print(
        f"  cases={real_report['cases']:,}, gate-only={real_report['gate_only_cases']}, "
        f"Gate Out before final yard (>{args.real_overlap_tolerance_min:g} min)="
        f"{real_report.get('gate_out_before_final_yard_cases', 0)}"
    )
    print("[contract] Simulated log")
    print(
        f"  cases={sim_report['cases']:,}, gate-only={sim_report['gate_only_cases']}, "
        f"within-case overlap={sim_report.get('within_case_overlap_cases', 0)}, "
        f"Gate Out before final yard={sim_report.get('gate_out_before_final_yard_cases', 0)}"
    )
    print(f"[contract] Audit -> {result_path}")
    print(f"[contract] Routing -> {out_dir / 'routing_comparison.csv'}")

    if sim_failures and args.fail_on_sim_violations:
        print(f"[contract] FAILED simulated case contract: {sim_failures}", file=sys.stderr)
        return 1
    print("[contract] PASSED")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (EventLogContractError, FileNotFoundError, KeyError, ValueError) as exc:
        print(f"[contract] FAILED: {exc}", file=sys.stderr)
        sys.exit(1)
